TOP_MESSAGE_COUNT = 5
TOP_CHARACTER_COUNT = 5
TOP_CHARACTER_PER_MESSAGE = 5
TOP_WEEKDAYS_COUNT = 7
TOP_STREAK_PEOPLE_COUNT = 5
TOP_STREAK_STREAKS_COUNT = 3
REALLY_BIG_NUMBER = 100000

DATE_FULL_FORMAT = '%Y-%m-%dT%H:%M:%S'
DATE_SHORT_FORMAT = '%Y-%m-%d'
DATE_WEEKDAY_READABLE_FORMAT = '%A'
DATE_HOUR_FORMAT = '%H'
